# Generated by Django 4.1.5 on 2023-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa_terciarizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo_empresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=50)),
            ],
        ),
    ]
